#!/system/bin/sh
# [[file:~/src/github/cuty/README.org::script-on-phone][script-on-phone]]
set
(
    toast() {
        am startservice --user 0 -n com.bhj.setclip/.PutClipService --es toast "$1"
    }

    log() {
        echo "$(date): $*" >> /sdcard/charcon.txt
    }

    cd /data/data/com.android.shell/
    mkdir -p var
    (
        flock -n 9 || exit 0
        sleep_secs=180

        while true; do
            capa=$(cat /sys/class/power_supply/battery/capacity)
            status=$(cat /sys/class/power_supply/battery/status)
            if let "capa < 15"; then
                echo 0 > /sys/class/power_supply/battery/input_suspend
                sleep 1
                if test "$(cat /sys/class/power_supply/battery/status)" = 'Not charging'; then
                    echo 1 > /sys/class/power_supply/battery/input_suspend
                    sleep 1
                    echo 0 > /sys/class/power_supply/battery/input_suspend
                    log "tried to restart charging"
                fi

                log "cap is $capa, status is $status, suspend is 0"
            elif let "capa > 95"; then
                echo 1 > /sys/class/power_supply/battery/input_suspend
                log "cap is $capa, suspend is 1"
            else
                true toast "capa is $capa"
                log "cap is $capa, suspend is $(cat /sys/class/power_supply/battery/input_suspend)"
            fi

            sleep $sleep_secs || true
        done
    ) 9> var/watch-my-battery.lock
)
# script-on-phone ends here
