* Cuty

Cuty stands for Cut Ur Tittytainment, not cut ur titty for entertainment.

It's a shell script for *Android* cell phones that help me quit the addiction to the Social Media on my cell phone.

What's more, in addition to get rid of the bad addiction, it trys to help me create 2 new good habits:

- Remind me to do 10 squats
- Open Kindle for me, remind me to do some real reading

** [[https://github.com/baohaojun/cuty/blob/master/watch-phone.sh][Script on the phone]]

The following is a simple script that runs on the phone, in the background.

It works by checking the current focused window, if it is “addictive” (such as weibo, weixin, facebook, or twitter: you can configure the list yourself), then it will take you back to your phone's HOME screen, open Kindle app, and prompt you to do 10 squats (so that you [[https://www.youtube.com/watch?v=N60bMFqkcpU][get rid of a bad habit while also get into a good habit]]).

By default, it checks every 3 minutes, but once you get caught, it will check every 3 seconds for half a minute, in case you might try to “sneak” back into the forbidden App.

#+name: script-on-phone
#+BEGIN_SRC sh :tangle ~/src/github/cuty/cuty :comments link :shebang "#!/system/bin/sh" :noweb yes

  set
  (
      toast() {
          am startservice --user 0 -n com.bhj.setclip/.PutClipService --es toast "$1"
          sh /system/bin/input keyevent HOME
          am start com.amazon.kindle/.UpgradePage
      }

      cd /data/data/com.android.shell/
      mkdir -p var
      (
          flock -n 9 || exit 0
          sleep_secs=180 # 每次最多玩 3 分钟

          times=0
          while true; do
              top_window=$(dumpsys window | sed -n '
  # {%sed-mode%}
  /mFocusedWindow=/{s,.* \(.*\)},\1,; p}
  # {%/sed-mode%}
  '
                        )
              case "$top_window" in
                  ,*weibo*)
                      toast "包昊军，不可以一直玩儿哦，去做 10 个深蹲！"
                      sleep_secs=3
                      times=0
                      ;;
                  ,*com.tencent.mm/*brandservice.ui.timeline*|com.weico.*)
                      toast "包昊军，不可以一直玩儿哦，去做 10 个深蹲！"
                      ;;
                  org.mozilla.firefox/*|com.android.chrome/*)
                      toast "包昊军，不可以一直玩儿哦，去做 10 个深蹲！"
                      sleep_secs=300
                      ;;
                  ,*onmyoji*)
                      toast "包昊军，不可以一直玩儿哦，去做 10 个深蹲！"
                      sleep_secs=300
                      ;;
                  ,*)
                      if let "times++ > 10"; then
                          sleep_secs=180
                          # There is no need to worry that TIMES will
                          # overflow, I can't live that long.
                      fi
                      ;;
              esac

              sleep $sleep_secs || true
          done
      ) 9> var/watch-my-window.lock
  )
#+END_SRC

** [[https://github.com/baohaojun/cuty/blob/master/start-watching][Script on the PC]]

This script runs on my Linux PC. It is used to start the script on the phone. You can also pass the =-u= option if you want to upload a new version of the =cuty= script.

#+name: start-cuty
#+BEGIN_SRC sh :tangle ~/src/github/cuty/start-cuty :comments link :shebang "#!/usr/bin/env bash" :noweb yes
  set -e

  abs0=$BASH_SOURCE
  if ! [[ $abs0 =~ ^/ ]]; then
      if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
          abs0=$PWD/$abs0
      elif test -e "$(which $BASH_SOURCE)"; then
          abs0=$(which $BASH_SOURCE)
      else
          die "Can't find abs path for $BASH_SOURCE"
      fi
  fi

  adb shell mkdir -p /data/data/com.android.shell/bin/
  if test $# = 0; then
      set -- ${abs0%/*}/cuty
  fi
  adb push "${1}" /data/data/com.android.shell/bin/cuty
  my-adb sc-shell fuser -k /data/data/com.android.shell/var/watch-my-window.lock || true

  shift
  adb-bg -l nohup.wp sh /data/data/com.android.shell/bin/cuty "$@"
#+END_SRC

** Additional infomation

*** How to run

To use these scripts, you will need:

- An Android phone
- Adb must be enable for the phone, root is *NOT* required
- You will need my [[https://github.com/baohaojun/system-config][system-config]] project, in which

  - =adb-bg= is a script that start a program on the phone through adb, but put it running in the background, so that after you disconnect the USB, it continues to run.
  - =fuser= is from busybox, whose ARM binary is included in system-config, which is used to stop the program when I need to upgrade the phone script
  - flock is from Android, part of toybox, which is used to make sure only 1 process is running

- You will also need my [[https://github.com/baohaojun/Wrench/][Wrench]] project, with which
  - I provided an Apk that allow to show Toast from the adb command line
  - I can start a program through adb every time my phone is connected

*** How to start it

1. Make sure your Android phone is connected to PC through adb.
2. Run =start-cuty=.

*** How to stop it

Reboot your phone☺.
