#!/bin/bash
# [[file:~/src/github/cuty/README.org::start-watch-phone][start-watch-phone]]
set -e
declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # uupdate-script
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o uh \
                      --long update-script,help,no-update-script \
                      -n $(basename -- $0) -- "$@")
declare update_script=false
eval set -- "$TEMP"
while true; do
    case "$1" in

        -u|--update-script|--no-update-script)
            if test "$1" = --no-update-script; then
                update_script=false
            else
                update_script=true
            fi
            shift

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-u, '
            printf %-24s '--[no-]update-script'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

me=$(readlink -f $BASH_SOURCE)
if test ! -e "$me"; then
    me=$(readlink -f "$(which $BASH_SOURCE)")
    if test ! -e "$me"; then
        die "Can't find out about me"
        exit 1
    fi
fi

abs0=$BASH_SOURCE
if ! [[ $abs0 =~ ^/ ]]; then
    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
        abs0=$PWD/$abs0
    elif test -e "$(which $BASH_SOURCE)"; then
        abs0=$(which $BASH_SOURCE)
    else
        die "Can't find abs path for $BASH_SOURCE"
    fi
fi

b0=$(basename $BASH_SOURCE)

if test "${update_script}" = true; then
    adb shell mkdir -p /data/data/com.android.shell/bin/
    adb push ${abs0%/*}/watch-phone.sh /data/data/com.android.shell/bin/
    my-adb sc-shell fuser -k /data/data/com.android.shell/var/watch-my-window.lock || true
fi

adb-bg sh /data/data/com.android.shell/bin/watch-phone.sh
# start-watch-phone ends here
