#!/bin/bash
# [[file:~/src/github/cuty/README.org::start-cuty][start-cuty]]
set -e

abs0=$BASH_SOURCE
if ! [[ $abs0 =~ ^/ ]]; then
    if [[ $abs0 =~ / ]] && test -e $PWD/$abs0; then
        abs0=$PWD/$abs0
    elif test -e "$(which $BASH_SOURCE)"; then
        abs0=$(which $BASH_SOURCE)
    else
        die "Can't find abs path for $BASH_SOURCE"
    fi
fi

adb shell mkdir -p /data/data/com.android.shell/bin/
adb push ${abs0%/*}/cuty /data/data/com.android.shell/bin/
my-adb sc-shell fuser -k /data/data/com.android.shell/var/watch-my-window.lock || true

adb-bg -l nohup.wp sh /data/data/com.android.shell/bin/cuty
# start-cuty ends here
